### ISSUE TITLE
ImportError due to hypothesis incompatibility

### ISSUE THREAD

**Issue by DerWeh** [uber/hypothesis-gufunc#2]
There seem to be incompatibilities with different versions of hypothesis.

With `hypothesis-5.1.0` I got the error:
```
    from hypothesis_gufunc.gufunc import gufunc_args                                                                                                                                                          
../../.pyenv/versions/3.6.1/lib/python3.6/site-packages/hypothesis_gufunc/gufunc.py:28: in <module>                                                                                                           
    from hypothesis.searchstrategy import SearchStrategy                                                                                                                                                      
E   ImportError: cannot import name 'SearchStrategy'
```

I tried upgrading to `hypothesis-5.1.5` giving now the error:
```

    from hypothesis_gufunc.gufunc import gufunc_args                                                                                                                                                          
../../.pyenv/versions/3.6.1/lib/python3.6/site-packages/hypothesis_gufunc/gufunc.py:26: in <module>                                                                                                           
    from hypothesis.internal.compat import integer_types                                                                                                                                                      
E   ImportError: cannot import name 'integer_types'
```

Going back to `hypothesis=4.24.5` fixed this issues.
Please specify for now the working version of `hypothesis` in the setup file, of course for the future it would be great to support the current version of `hypothesis`.

Besides this, thank you so much for this great module, it really is a godsend.

**Comment by Zac-HD** [comment]
@DerWeh - since [Hypothesis 4.44 (November)](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-44-0), there's been [a `mutually_broadcastable_shapes()` strategy upstream](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes).  While it gives you shapes rather than arrays, it also has considerably better performance when shrinking.

(@rdturnermtl - perhaps you could rebase `hypothesis-gufunc`'s internals on this?)

**Comment by rdturnermtl** [comment]
The pinned version of hypothesis (and other packages) that this has been tested with is in `requirements/`. The hypothesis version being in `requirements/base.in`.

It looks like hypothesis has had some API changes with version 5. I will look at this for maintaining compatibility.

**Comment by Zac-HD** [comment]
We've moved some private internals around (which it looks like this package is using), but the public API hasn't changed much at all.

**Comment by rdturnermtl** [comment]
It looks like problem 1 is because:
`hypothesis.searchstrategy.SearchStrategy`
has been moved to
`hypothesis.strategies._internal.SearchStrategy`

Is there any way to check `isinstance(shapes, SearchStrategy)` without having to import from private in hypothesis 5?

The other issue is that `hypothesis.internal.compat.integer_types` has been removed following the Py2 deprecation.  This is an easy fix, because `hypothesis_gufunc` can just use `int` by dropping Py2 support as well.

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/details.html#hypothesis.strategies.SearchStrategy

Our API guidelines are to strictly avoid anything which could be a value or a strategy (`just()` is easy!), but if that's not on the table you can still use the public location.

**Comment by rdturnermtl** [comment]
Requiring a strategy might be a good change for a major increment, but I think I will keep the API the same in this small patch.  It was based on the old behavior of `arrays` but I guess that has changed now?

**Comment by Zac-HD** [comment]
`arrays()` has not changed, since we are serious about compatibility for our public API and expect that many people rely on the current behaviour.

It was our experience using and teaching `arrays()` that prompted that particular [API style rule](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/api-style.rst#argument-handling) - IMO once you want to test with varied shapes and broadcasting it's usually more elegant to use the `st.data()` strategy to draw values inside your test.  numpy/numpy#15189 provides a well commented example of this style while using `mutually_broadcastable_shapes()` to test `np.clip()`.

I'm not *delighted* by this split between simple uses (in `@given(...)`) and complex uses (in the test), but on balance I think making the inline approach - which works for any strategy and domain - as approachable as possible is better than adding an intermediate API specific to Numpy.

That's also the short version of why we don't have a `mutually_broadcastable_arrays()` strategy upstream - IMO by the time a user needs that, we should be pushing them towards inline `st.data()` or defining their own with `@st.composite` anyway.

**Comment by rdturnermtl** [comment]
I have pushed a branch [fix_issue_2](https://github.com/uber/hypothesis-gufunc/tree/fix_issue_2) that should work. @DerWeh and @Zac-HD can take a look and see if there are any issues with that. I can merge if that resolves all the issues.

Bigger changes like switching to `mutually_broadcastable_shapes` can wait for another diff.

**Comment by Zac-HD** [comment]
In your test file you only use `integer_types` once and `hunichr` twice, so it'd be a smaller diff to replace them than define and comment the variables.  I'd also suggest adding `python_requires=">=3.6",` in `setup.py` to explicitly block install on unsupported versions, and adding the classifiers for 3.7 and 3.8 since you're testing those now.  Otherwise it looks good to me!

Agreed that the other stuff can wait 👍

**Comment by rdturnermtl** [comment]
I made those cleanups to `setup.py`.

@Zac-HD can you file a separate issue for `mutually_broadcastable_shapes`, and explain its difference with `gufunc_arg_shapes`? Or a PR would be even better.

**Comment by Zac-HD** [comment]
Comparing the docs for [`gufunc_arg_shapes()`](https://hypothesis-gufunc.readthedocs.io/en/latest/code.html#hypothesis_gufunc.gufunc.gufunc_arg_shapes) to [`mutually_broadcastable_shapes()`](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes), there are several differences - upstream:

- supports lower bounds on number of loop dimensions (both support upper)
- uses the same API for `ufunc` shapes (e.g. specify `num_inputs=2` for `np.add`)
- returns a namedtuple `BroadcastableShapes(input_shapes=..., result_shape=...)` to facilitate gufunc result shape checks (signatures + broadcasting -> headache)
- has much better shrinking performance.
- does not support the `excluded` argument
- does not support per-dimension size bounds

The proper use of `excluded` isn't clear to me, but it's possible to adapt everything else (though per-dim bounds require either upstream support, or flatmapping over rewritten signatures...).

------------

I think the actual challenge here is not implementation though, it's designing a really nice API and that in turn means we all need to understand the users and use-cases.  If you're coming to PyCon US we could meet up with @rsokl and hash it out in person?  Otherwise maybe a teleconference or something, but text is awkwardly low-bandwidth for this...

**Comment by rdturnermtl** [comment]
This issue has been resolved and merged to master. The version has been bumped to `0.0.6`.
